export * from './password.rule'
export * from './email.rule'
export * from './name.rule'
export * from './phone.rule'
export * from './min.rule'
export * from './max.rule'
export * from './alpha-spaces.rule'
export * from './required.rule'
