// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LirestLogo: typeof import('./components/LirestLogo.vue')['default']
    LoginButton: typeof import('./components/LoginButton.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MainNavBar: typeof import('./components/MainNavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterButton: typeof import('./components/RegisterButton.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryNavBar: typeof import('./components/SecondaryNavBar.vue')['default']
    SlideShow: typeof import('./components/SlideShow.vue')['default']
  }
}

export {}
