// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHorizontalLine: typeof import('./components/BaseHorizontalLine.vue')['default']
    BaseTransition: typeof import('./components/BaseTransition.vue')['default']
    ContentToggler: typeof import('./components/ContentToggler.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    IconAbout: typeof import('./components/IconAbout.vue')['default']
    IconGithub: typeof import('./components/IconGithub.vue')['default']
    IconHome: typeof import('./components/IconHome.vue')['default']
    IconLocale: typeof import('./components/IconLocale.vue')['default']
    IconToggleDarkMode: typeof import('./components/IconToggleDarkMode.vue')['default']
    InputSelectLocale: typeof import('./components/InputSelectLocale.vue')['default']
    LirestLogo: typeof import('./components/LirestLogo.vue')['default']
    LirestPersonalLogo: typeof import('./components/LirestPersonalLogo.vue')['default']
    LoginButton: typeof import('./modules/auth/components/LoginButton.vue')['default']
    LoginForm: typeof import('./modules/auth/components/LoginForm.vue')['default']
    NavBarMain: typeof import('./components/NavBarMain.vue')['default']
    NavBarSecondary: typeof import('./components/NavBarSecondary.vue')['default']
    NavBarSticky: typeof import('./components/NavBarSticky.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterButton: typeof import('./modules/auth/components/RegisterButton.vue')['default']
    RegisterForm: typeof import('./modules/auth/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideShow: typeof import('./components/SlideShow.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ToastMessage: typeof import('./components/ToastMessage.vue')['default']
    UserHeader: typeof import('./modules/users/components/UserHeader.vue')['default']
    UserLogo: typeof import('./modules/users/components/UserLogo.vue')['default']
    UserMiniMenu: typeof import('./modules/users/components/UserMiniMenu.vue')['default']
    UserNotificationLogo: typeof import('./modules/users/components/UserNotificationLogo.vue')['default']
    UserSettingLogo: typeof import('./modules/users/components/UserSettingLogo.vue')['default']
  }
}

export {}
